### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by alowell-ssl** [PhilippeBekaert/snd-hdspe#5]
Hi, I just cloned commit cc8621559834a7b18de7285c518bddcf26b522b8.  I'm on Ubuntu 20.04 LTS, kernel is 5.4.0-91-lowlatency

Going through your instructions, compilation fails with:
![image](https://user-images.githubusercontent.com/25305416/147769246-ccc0f71d-2db6-4587-aa27-fc33e54e84b4.png)

**Comment by PhilippeBekaert** [comment]
Strange. I’m also on Ubuntu 20.04 lowlatency. I’m currently out of office but will check asap what has happened with snd_card.sync_irq. Thanks for reporting. Happy new year. Ph

**Comment by PhilippeBekaert** [comment]
I see I'm on a later version of the kernel: 5.11.0-43. Is it an option for you to update/upgrade your system?

Or you could try commenting out that offending line 464. It's an addition to audio drivers dating back to the end of 2019. (Just that single line added to the hdspm driver at that time. hdspe is based on hdspm.)

However, you may end up finding other compilation issues due to changes in the kernel alsa subsystem since your kernel version.

Let me know how it works out, and thanks again for reporting.

Best,

Philippe.

**Comment by alowell-ssl** [comment]
Hi Philippe,

Thanks for your attention! I commented out the line and the compilation was
successful.  I'll give it a shot soon.  I think I got everything working
stably with the stock hdsp kernel module (this took 1-2 days of messing
with my system), but I'm still curious to try your module.  Do you think
your module offers anything in the way of reducing xruns compared to the
stock module?

Happy new year,
Alex

**Comment by PhilippeBekaert** [comment]
What card are you using the driver with? Hdsp and hdspm were already pretty optimal wrt xruns. My driver will be similar I expect. In any case it was not worse in my tests. I fixed several issues, especially wrt double and quad speed, implemented support for the new aio pro, completed the feature set and wrote a user space configuration tool similar to those of rme on other platforms, but in terms of xrun performance I do not think there was much to improve. (I have no xruns btw even on small buffer sizes, but that may be different on older or less powerful hardware). Best, ph

**Comment by alowell-ssl** [comment]
Hi Philippe,

Thanks, I'm using the AIO (non-pro).  I have a pretty modern desktop, and
finally got rid of xruns (mostly) after fiddling with many settings.  I
still get some if I'm using certain browser apps (for example, just loading
a big google doc will cause a huge burst of xruns), but otherwise it runs
smooth even with high DSP load. The final source of xruns that I tracked
down was probably not related to the driver.  Instead, I think I just
wasn't running jackd with high enough priority, so background system tasks
were preempting and causing xruns (figured this out by watching the xrun
counter and journalctl -f at the same time).

Just curious, how does one go about writing driver code for commercial
hardware?  Did RME give you information on which registers do what? Or was
this all reverse engineered?

Thanks,
Alex

**Comment by PhilippeBekaert** [comment]
Hi Alex,

The AIO is supported perfectly well. I've been using these cards for many years myself too, including television broadcasting and live streaming. Finding out RME discontinued the production of the AIO and now offers the AIO Pro, which was not supported by the hdspm driver, was the trigger that made me develop the new driver.
jack thread priority helps, and a low latency kernel too (ubuntu studio e.g.).
There is no reverse engineering in this driver. RME was so kind to share their windows and mac driver source code with me.
Best,
Philippe.
